#!/bin/bash

# EMS Backend - GitHub & Render Deployment Script
# Run this on your machine with your GitHub credentials

echo "🚀 EMS Backend - GitHub & Render Deployment"
echo "==========================================="
echo ""

# STEP 1: Push to GitHub
echo "📝 STEP 1: Setting up GitHub remote"
echo "-----------------------------------"
git remote remove origin 2>/dev/null || true
git remote add origin https://github.com/saeedafri/Employee-management-system.git
git branch -M main

echo "Pushing code to GitHub (you may be prompted to log in)..."
git push -u origin main

echo "✅ Code pushed to GitHub!"
echo ""

# STEP 2: Show what's been pushed
echo "📦 STEP 2: Verifying GitHub"
echo "-----------------------------------"
echo "Visit: https://github.com/saeedafri/Employee-management-system"
echo "You should see all code and documentation"
echo ""

# STEP 3: Render deployment instructions
echo "🚀 STEP 3: Deploying to Render"
echo "-----------------------------------"
echo ""
echo "Follow these steps in Render dashboard:"
echo ""
echo "1. Visit: https://dashboard.render.com/"
echo ""
echo "2. Click 'New +' button → 'Web Service'"
echo ""
echo "3. Connect GitHub Repository:"
echo "   - Select: saeedafri/Employee-management-system"
echo "   - Branch: main"
echo ""
echo "4. Configure Web Service:"
echo "   - Name: ems-backend"
echo "   - Region: Choose closest to you"
echo "   - Runtime: Node"
echo "   - Build Command: npm install && npm run db:migrate:prod"
echo "   - Start Command: npm start"
echo ""
echo "5. Add Environment Variables:"
echo "   Copy from .env file:"
echo "   - NODE_ENV=production"
echo "   - PORT=3000"
echo "   - DATABASE_URL=mysql://user:pass@host/db"
echo "   - REDIS_URL=redis://:pass@host:port"
echo "   - JWT_SECRET=your-secret"
echo "   - SMTP_HOST=smtp.ethereal.email"
echo "   - SMTP_PORT=587"
echo "   - SMTP_USER=xevntepfhndjlzz2@ethereal.email"
echo "   - SMTP_PASS=P9Jbx5AXVW1csWhhaE"
echo "   - SMTP_FROM=ems@ethereal.email"
echo ""
echo "6. Click 'Create Web Service'"
echo ""
echo "✅ Render will automatically deploy when you push to GitHub!"
echo ""

# STEP 4: MySQL Database on Render
echo "🗄️  STEP 4: Setting up MySQL Database"
echo "-----------------------------------"
echo ""
echo "Option A: Use Render MySQL (Recommended for easy setup)"
echo "  1. In Render dashboard, click 'New +' → 'MySQL'"
echo "  2. Name: ems-mysql"
echo "  3. Plan: Free (if available)"
echo "  4. Copy connection string to DATABASE_URL"
echo ""
echo "Option B: Use AWS RDS (More production-ready)"
echo "  1. Go to https://aws.amazon.com/rds"
echo "  2. Create MySQL 8.0 instance"
echo "  3. Copy connection string"
echo "  4. Paste as DATABASE_URL in Render environment"
echo ""
echo "After setting DATABASE_URL:"
echo "  - Render will automatically run migrations"
echo "  - Use: npm run db:migrate:prod"
echo ""

# STEP 5: Redis Configuration
echo "⚡ STEP 5: Setting up Redis"
echo "-----------------------------------"
echo ""
echo "Option A: Render Redis"
echo "  1. Click 'New +' → 'Redis'"
echo "  2. Name: ems-redis"
echo "  3. Plan: Free"
echo "  4. Copy connection string to REDIS_URL"
echo ""
echo "Option B: Redis Cloud (Free tier)"
echo "  1. Go to https://redis.com/try-free"
echo "  2. Create account and database"
echo "  3. Copy connection string"
echo "  4. Paste as REDIS_URL"
echo ""

# STEP 6: Verification
echo "✅ STEP 6: Verify Deployment"
echo "-----------------------------------"
echo ""
echo "After services are running:"
echo ""
echo "1. Check health endpoint:"
echo "   curl https://your-app.onrender.com/health"
echo "   Should return: {\"status\":\"ok\"}"
echo ""
echo "2. View logs:"
echo "   In Render dashboard → Logs tab"
echo "   Look for 'Server started' message"
echo ""
echo "3. Test API:"
echo "   POST https://your-app.onrender.com/api/v1/auth/login"
echo "   See API_DOCUMENTATION.md for examples"
echo ""

echo ""
echo "🎉 DEPLOYMENT COMPLETE!"
echo "==========================================="
echo ""
echo "📚 Next Steps:"
echo "  1. Share GitHub link with UI team"
echo "  2. Share API docs: API_DOCUMENTATION.md"
echo "  3. Test APIs with frontend team"
echo "  4. Monitor Render dashboard for errors"
echo ""
echo "📞 Support:"
echo "  - GitHub: https://github.com/saeedafri/Employee-management-system"
echo "  - Render: https://dashboard.render.com"
echo "  - Docs: See README_FINAL_STATUS.md"
echo ""
