// ISO-3166 country + ISO-4217 default-currency reference data + generic IBAN/BIC
// fallback fields. Ported VERBATIM from the FE source of truth
// (ems-frontend/src/modules/payroll/constants/iso-countries.ts). Config-over-code:
// reference facts, never a hardcoded country "rule".
/**
 * All ISO-3166-1 alpha-2 countries as `Country` rows. `currency` is the ISO-4217
 * default; `locale` defaults to `en-<CODE>`; `fiscalYearStartMonth` is 1 unless
 * the country starts its fiscal year elsewhere (IN/GB/NZ/JP = 4, AU/EG = 7, ZA = 3).
 * Reference data — stable facts, not tenant policy (CLAUDE.md §26: not a hardcoded "rule").
 */
export const ISO_COUNTRIES = [
  { code: 'AD', name: 'Andorra', currency: 'EUR', locale: 'en-AD', fiscalYearStartMonth: 1 },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    currency: 'AED',
    locale: 'en-AE',
    fiscalYearStartMonth: 1,
  },
  { code: 'AF', name: 'Afghanistan', currency: 'AFN', locale: 'en-AF', fiscalYearStartMonth: 1 },
  {
    code: 'AG',
    name: 'Antigua and Barbuda',
    currency: 'XCD',
    locale: 'en-AG',
    fiscalYearStartMonth: 1,
  },
  { code: 'AI', name: 'Anguilla', currency: 'XCD', locale: 'en-AI', fiscalYearStartMonth: 1 },
  { code: 'AL', name: 'Albania', currency: 'ALL', locale: 'en-AL', fiscalYearStartMonth: 1 },
  { code: 'AM', name: 'Armenia', currency: 'AMD', locale: 'en-AM', fiscalYearStartMonth: 1 },
  { code: 'AO', name: 'Angola', currency: 'AOA', locale: 'en-AO', fiscalYearStartMonth: 1 },
  { code: 'AQ', name: 'Antarctica', currency: 'USD', locale: 'en-AQ', fiscalYearStartMonth: 1 },
  { code: 'AR', name: 'Argentina', currency: 'ARS', locale: 'en-AR', fiscalYearStartMonth: 1 },
  { code: 'AS', name: 'American Samoa', currency: 'USD', locale: 'en-AS', fiscalYearStartMonth: 1 },
  { code: 'AT', name: 'Austria', currency: 'EUR', locale: 'en-AT', fiscalYearStartMonth: 1 },
  { code: 'AU', name: 'Australia', currency: 'AUD', locale: 'en-AU', fiscalYearStartMonth: 7 },
  { code: 'AW', name: 'Aruba', currency: 'AWG', locale: 'en-AW', fiscalYearStartMonth: 1 },
  { code: 'AX', name: 'Åland Islands', currency: 'EUR', locale: 'en-AX', fiscalYearStartMonth: 1 },
  { code: 'AZ', name: 'Azerbaijan', currency: 'AZN', locale: 'en-AZ', fiscalYearStartMonth: 1 },
  {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    currency: 'BAM',
    locale: 'en-BA',
    fiscalYearStartMonth: 1,
  },
  { code: 'BB', name: 'Barbados', currency: 'BBD', locale: 'en-BB', fiscalYearStartMonth: 1 },
  { code: 'BD', name: 'Bangladesh', currency: 'BDT', locale: 'en-BD', fiscalYearStartMonth: 1 },
  { code: 'BE', name: 'Belgium', currency: 'EUR', locale: 'en-BE', fiscalYearStartMonth: 1 },
  { code: 'BF', name: 'Burkina Faso', currency: 'XOF', locale: 'en-BF', fiscalYearStartMonth: 1 },
  { code: 'BG', name: 'Bulgaria', currency: 'BGN', locale: 'en-BG', fiscalYearStartMonth: 1 },
  { code: 'BH', name: 'Bahrain', currency: 'BHD', locale: 'en-BH', fiscalYearStartMonth: 1 },
  { code: 'BI', name: 'Burundi', currency: 'BIF', locale: 'en-BI', fiscalYearStartMonth: 1 },
  { code: 'BJ', name: 'Benin', currency: 'XOF', locale: 'en-BJ', fiscalYearStartMonth: 1 },
  {
    code: 'BL',
    name: 'Saint Barthélemy',
    currency: 'EUR',
    locale: 'en-BL',
    fiscalYearStartMonth: 1,
  },
  { code: 'BM', name: 'Bermuda', currency: 'BMD', locale: 'en-BM', fiscalYearStartMonth: 1 },
  {
    code: 'BN',
    name: 'Brunei Darussalam',
    currency: 'BND',
    locale: 'en-BN',
    fiscalYearStartMonth: 1,
  },
  { code: 'BO', name: 'Bolivia', currency: 'BOB', locale: 'en-BO', fiscalYearStartMonth: 1 },
  {
    code: 'BQ',
    name: 'Bonaire, Sint Eustatius and Saba',
    currency: 'USD',
    locale: 'en-BQ',
    fiscalYearStartMonth: 1,
  },
  { code: 'BR', name: 'Brazil', currency: 'BRL', locale: 'en-BR', fiscalYearStartMonth: 1 },
  { code: 'BS', name: 'Bahamas', currency: 'BSD', locale: 'en-BS', fiscalYearStartMonth: 1 },
  { code: 'BT', name: 'Bhutan', currency: 'BTN', locale: 'en-BT', fiscalYearStartMonth: 1 },
  { code: 'BV', name: 'Bouvet Island', currency: 'NOK', locale: 'en-BV', fiscalYearStartMonth: 1 },
  { code: 'BW', name: 'Botswana', currency: 'BWP', locale: 'en-BW', fiscalYearStartMonth: 1 },
  { code: 'BY', name: 'Belarus', currency: 'BYN', locale: 'en-BY', fiscalYearStartMonth: 1 },
  { code: 'BZ', name: 'Belize', currency: 'BZD', locale: 'en-BZ', fiscalYearStartMonth: 1 },
  { code: 'CA', name: 'Canada', currency: 'CAD', locale: 'en-CA', fiscalYearStartMonth: 1 },
  {
    code: 'CC',
    name: 'Cocos (Keeling) Islands',
    currency: 'AUD',
    locale: 'en-CC',
    fiscalYearStartMonth: 1,
  },
  {
    code: 'CD',
    name: 'Congo, Democratic Republic',
    currency: 'CDF',
    locale: 'en-CD',
    fiscalYearStartMonth: 1,
  },
  {
    code: 'CF',
    name: 'Central African Republic',
    currency: 'XAF',
    locale: 'en-CF',
    fiscalYearStartMonth: 1,
  },
  { code: 'CG', name: 'Congo', currency: 'XAF', locale: 'en-CG', fiscalYearStartMonth: 1 },
  { code: 'CH', name: 'Switzerland', currency: 'CHF', locale: 'en-CH', fiscalYearStartMonth: 1 },
  { code: 'CI', name: 'Côte d\'Ivoire', currency: 'XOF', locale: 'en-CI', fiscalYearStartMonth: 1 },
  { code: 'CK', name: 'Cook Islands', currency: 'NZD', locale: 'en-CK', fiscalYearStartMonth: 1 },
  { code: 'CL', name: 'Chile', currency: 'CLP', locale: 'en-CL', fiscalYearStartMonth: 1 },
  { code: 'CM', name: 'Cameroon', currency: 'XAF', locale: 'en-CM', fiscalYearStartMonth: 1 },
  { code: 'CN', name: 'China', currency: 'CNY', locale: 'en-CN', fiscalYearStartMonth: 1 },
  { code: 'CO', name: 'Colombia', currency: 'COP', locale: 'en-CO', fiscalYearStartMonth: 1 },
  { code: 'CR', name: 'Costa Rica', currency: 'CRC', locale: 'en-CR', fiscalYearStartMonth: 1 },
  { code: 'CU', name: 'Cuba', currency: 'CUP', locale: 'en-CU', fiscalYearStartMonth: 1 },
  { code: 'CV', name: 'Cabo Verde', currency: 'CVE', locale: 'en-CV', fiscalYearStartMonth: 1 },
  { code: 'CW', name: 'Curaçao', currency: 'ANG', locale: 'en-CW', fiscalYearStartMonth: 1 },
  {
    code: 'CX',
    name: 'Christmas Island',
    currency: 'AUD',
    locale: 'en-CX',
    fiscalYearStartMonth: 1,
  },
  { code: 'CY', name: 'Cyprus', currency: 'EUR', locale: 'en-CY', fiscalYearStartMonth: 1 },
  { code: 'CZ', name: 'Czechia', currency: 'CZK', locale: 'en-CZ', fiscalYearStartMonth: 1 },
  { code: 'DE', name: 'Germany', currency: 'EUR', locale: 'en-DE', fiscalYearStartMonth: 1 },
  { code: 'DJ', name: 'Djibouti', currency: 'DJF', locale: 'en-DJ', fiscalYearStartMonth: 1 },
  { code: 'DK', name: 'Denmark', currency: 'DKK', locale: 'en-DK', fiscalYearStartMonth: 1 },
  { code: 'DM', name: 'Dominica', currency: 'XCD', locale: 'en-DM', fiscalYearStartMonth: 1 },
  {
    code: 'DO',
    name: 'Dominican Republic',
    currency: 'DOP',
    locale: 'en-DO',
    fiscalYearStartMonth: 1,
  },
  { code: 'DZ', name: 'Algeria', currency: 'DZD', locale: 'en-DZ', fiscalYearStartMonth: 1 },
  { code: 'EC', name: 'Ecuador', currency: 'USD', locale: 'en-EC', fiscalYearStartMonth: 1 },
  { code: 'EE', name: 'Estonia', currency: 'EUR', locale: 'en-EE', fiscalYearStartMonth: 1 },
  { code: 'EG', name: 'Egypt', currency: 'EGP', locale: 'en-EG', fiscalYearStartMonth: 7 },
  { code: 'EH', name: 'Western Sahara', currency: 'MAD', locale: 'en-EH', fiscalYearStartMonth: 1 },
  { code: 'ER', name: 'Eritrea', currency: 'ERN', locale: 'en-ER', fiscalYearStartMonth: 1 },
  { code: 'ES', name: 'Spain', currency: 'EUR', locale: 'en-ES', fiscalYearStartMonth: 1 },
  { code: 'ET', name: 'Ethiopia', currency: 'ETB', locale: 'en-ET', fiscalYearStartMonth: 1 },
  { code: 'FI', name: 'Finland', currency: 'EUR', locale: 'en-FI', fiscalYearStartMonth: 1 },
  { code: 'FJ', name: 'Fiji', currency: 'FJD', locale: 'en-FJ', fiscalYearStartMonth: 1 },
  {
    code: 'FK',
    name: 'Falkland Islands (Malvinas)',
    currency: 'FKP',
    locale: 'en-FK',
    fiscalYearStartMonth: 1,
  },
  {
    code: 'FM',
    name: 'Micronesia, Federated States',
    currency: 'USD',
    locale: 'en-FM',
    fiscalYearStartMonth: 1,
  },
  { code: 'FO', name: 'Faroe Islands', currency: 'DKK', locale: 'en-FO', fiscalYearStartMonth: 1 },
  { code: 'FR', name: 'France', currency: 'EUR', locale: 'en-FR', fiscalYearStartMonth: 1 },
  { code: 'GA', name: 'Gabon', currency: 'XAF', locale: 'en-GA', fiscalYearStartMonth: 1 },
  { code: 'GB', name: 'United Kingdom', currency: 'GBP', locale: 'en-GB', fiscalYearStartMonth: 4 },
  { code: 'GD', name: 'Grenada', currency: 'XCD', locale: 'en-GD', fiscalYearStartMonth: 1 },
  { code: 'GE', name: 'Georgia', currency: 'GEL', locale: 'en-GE', fiscalYearStartMonth: 1 },
  { code: 'GF', name: 'French Guiana', currency: 'EUR', locale: 'en-GF', fiscalYearStartMonth: 1 },
  { code: 'GG', name: 'Guernsey', currency: 'GBP', locale: 'en-GG', fiscalYearStartMonth: 1 },
  { code: 'GH', name: 'Ghana', currency: 'GHS', locale: 'en-GH', fiscalYearStartMonth: 1 },
  { code: 'GI', name: 'Gibraltar', currency: 'GIP', locale: 'en-GI', fiscalYearStartMonth: 1 },
  { code: 'GL', name: 'Greenland', currency: 'DKK', locale: 'en-GL', fiscalYearStartMonth: 1 },
  { code: 'GM', name: 'Gambia', currency: 'GMD', locale: 'en-GM', fiscalYearStartMonth: 1 },
  { code: 'GN', name: 'Guinea', currency: 'GNF', locale: 'en-GN', fiscalYearStartMonth: 1 },
  { code: 'GP', name: 'Guadeloupe', currency: 'EUR', locale: 'en-GP', fiscalYearStartMonth: 1 },
  {
    code: 'GQ',
    name: 'Equatorial Guinea',
    currency: 'XAF',
    locale: 'en-GQ',
    fiscalYearStartMonth: 1,
  },
  { code: 'GR', name: 'Greece', currency: 'EUR', locale: 'en-GR', fiscalYearStartMonth: 1 },
  {
    code: 'GS',
    name: 'South Georgia and South Sandwich Islands',
    currency: 'GBP',
    locale: 'en-GS',
    fiscalYearStartMonth: 1,
  },
  { code: 'GT', name: 'Guatemala', currency: 'GTQ', locale: 'en-GT', fiscalYearStartMonth: 1 },
  { code: 'GU', name: 'Guam', currency: 'USD', locale: 'en-GU', fiscalYearStartMonth: 1 },
  { code: 'GW', name: 'Guinea-Bissau', currency: 'XOF', locale: 'en-GW', fiscalYearStartMonth: 1 },
  { code: 'GY', name: 'Guyana', currency: 'GYD', locale: 'en-GY', fiscalYearStartMonth: 1 },
  { code: 'HK', name: 'Hong Kong', currency: 'HKD', locale: 'en-HK', fiscalYearStartMonth: 1 },
  {
    code: 'HM',
    name: 'Heard Island and McDonald Islands',
    currency: 'AUD',
    locale: 'en-HM',
    fiscalYearStartMonth: 1,
  },
  { code: 'HN', name: 'Honduras', currency: 'HNL', locale: 'en-HN', fiscalYearStartMonth: 1 },
  { code: 'HR', name: 'Croatia', currency: 'EUR', locale: 'en-HR', fiscalYearStartMonth: 1 },
  { code: 'HT', name: 'Haiti', currency: 'HTG', locale: 'en-HT', fiscalYearStartMonth: 1 },
  { code: 'HU', name: 'Hungary', currency: 'HUF', locale: 'en-HU', fiscalYearStartMonth: 1 },
  { code: 'ID', name: 'Indonesia', currency: 'IDR', locale: 'en-ID', fiscalYearStartMonth: 1 },
  { code: 'IE', name: 'Ireland', currency: 'EUR', locale: 'en-IE', fiscalYearStartMonth: 1 },
  { code: 'IL', name: 'Israel', currency: 'ILS', locale: 'en-IL', fiscalYearStartMonth: 1 },
  { code: 'IM', name: 'Isle of Man', currency: 'GBP', locale: 'en-IM', fiscalYearStartMonth: 1 },
  { code: 'IN', name: 'India', currency: 'INR', locale: 'en-IN', fiscalYearStartMonth: 4 },
  {
    code: 'IO',
    name: 'British Indian Ocean Territory',
    currency: 'USD',
    locale: 'en-IO',
    fiscalYearStartMonth: 1,
  },
  { code: 'IQ', name: 'Iraq', currency: 'IQD', locale: 'en-IQ', fiscalYearStartMonth: 1 },
  { code: 'IR', name: 'Iran', currency: 'IRR', locale: 'en-IR', fiscalYearStartMonth: 1 },
  { code: 'IS', name: 'Iceland', currency: 'ISK', locale: 'en-IS', fiscalYearStartMonth: 1 },
  { code: 'IT', name: 'Italy', currency: 'EUR', locale: 'en-IT', fiscalYearStartMonth: 1 },
  { code: 'JE', name: 'Jersey', currency: 'GBP', locale: 'en-JE', fiscalYearStartMonth: 1 },
  { code: 'JM', name: 'Jamaica', currency: 'JMD', locale: 'en-JM', fiscalYearStartMonth: 1 },
  { code: 'JO', name: 'Jordan', currency: 'JOD', locale: 'en-JO', fiscalYearStartMonth: 1 },
  { code: 'JP', name: 'Japan', currency: 'JPY', locale: 'en-JP', fiscalYearStartMonth: 4 },
  { code: 'KE', name: 'Kenya', currency: 'KES', locale: 'en-KE', fiscalYearStartMonth: 1 },
  { code: 'KG', name: 'Kyrgyzstan', currency: 'KGS', locale: 'en-KG', fiscalYearStartMonth: 1 },
  { code: 'KH', name: 'Cambodia', currency: 'KHR', locale: 'en-KH', fiscalYearStartMonth: 1 },
  { code: 'KI', name: 'Kiribati', currency: 'AUD', locale: 'en-KI', fiscalYearStartMonth: 1 },
  { code: 'KM', name: 'Comoros', currency: 'KMF', locale: 'en-KM', fiscalYearStartMonth: 1 },
  {
    code: 'KN',
    name: 'Saint Kitts and Nevis',
    currency: 'XCD',
    locale: 'en-KN',
    fiscalYearStartMonth: 1,
  },
  {
    code: 'KP',
    name: 'Korea, Democratic People\'s Republic',
    currency: 'KPW',
    locale: 'en-KP',
    fiscalYearStartMonth: 1,
  },
  {
    code: 'KR',
    name: 'Korea, Republic of',
    currency: 'KRW',
    locale: 'en-KR',
    fiscalYearStartMonth: 1,
  },
  { code: 'KW', name: 'Kuwait', currency: 'KWD', locale: 'en-KW', fiscalYearStartMonth: 1 },
  { code: 'KY', name: 'Cayman Islands', currency: 'KYD', locale: 'en-KY', fiscalYearStartMonth: 1 },
  { code: 'KZ', name: 'Kazakhstan', currency: 'KZT', locale: 'en-KZ', fiscalYearStartMonth: 1 },
  {
    code: 'LA',
    name: 'Lao People\'s Democratic Republic',
    currency: 'LAK',
    locale: 'en-LA',
    fiscalYearStartMonth: 1,
  },
  { code: 'LB', name: 'Lebanon', currency: 'LBP', locale: 'en-LB', fiscalYearStartMonth: 1 },
  { code: 'LC', name: 'Saint Lucia', currency: 'XCD', locale: 'en-LC', fiscalYearStartMonth: 1 },
  { code: 'LI', name: 'Liechtenstein', currency: 'CHF', locale: 'en-LI', fiscalYearStartMonth: 1 },
  { code: 'LK', name: 'Sri Lanka', currency: 'LKR', locale: 'en-LK', fiscalYearStartMonth: 1 },
  { code: 'LR', name: 'Liberia', currency: 'LRD', locale: 'en-LR', fiscalYearStartMonth: 1 },
  { code: 'LS', name: 'Lesotho', currency: 'LSL', locale: 'en-LS', fiscalYearStartMonth: 1 },
  { code: 'LT', name: 'Lithuania', currency: 'EUR', locale: 'en-LT', fiscalYearStartMonth: 1 },
  { code: 'LU', name: 'Luxembourg', currency: 'EUR', locale: 'en-LU', fiscalYearStartMonth: 1 },
  { code: 'LV', name: 'Latvia', currency: 'EUR', locale: 'en-LV', fiscalYearStartMonth: 1 },
  { code: 'LY', name: 'Libya', currency: 'LYD', locale: 'en-LY', fiscalYearStartMonth: 1 },
  { code: 'MA', name: 'Morocco', currency: 'MAD', locale: 'en-MA', fiscalYearStartMonth: 1 },
  { code: 'MC', name: 'Monaco', currency: 'EUR', locale: 'en-MC', fiscalYearStartMonth: 1 },
  { code: 'MD', name: 'Moldova', currency: 'MDL', locale: 'en-MD', fiscalYearStartMonth: 1 },
  { code: 'ME', name: 'Montenegro', currency: 'EUR', locale: 'en-ME', fiscalYearStartMonth: 1 },
  {
    code: 'MF',
    name: 'Saint Martin (French part)',
    currency: 'EUR',
    locale: 'en-MF',
    fiscalYearStartMonth: 1,
  },
  { code: 'MG', name: 'Madagascar', currency: 'MGA', locale: 'en-MG', fiscalYearStartMonth: 1 },
  {
    code: 'MH',
    name: 'Marshall Islands',
    currency: 'USD',
    locale: 'en-MH',
    fiscalYearStartMonth: 1,
  },
  {
    code: 'MK',
    name: 'North Macedonia',
    currency: 'MKD',
    locale: 'en-MK',
    fiscalYearStartMonth: 1,
  },
  { code: 'ML', name: 'Mali', currency: 'XOF', locale: 'en-ML', fiscalYearStartMonth: 1 },
  { code: 'MM', name: 'Myanmar', currency: 'MMK', locale: 'en-MM', fiscalYearStartMonth: 1 },
  { code: 'MN', name: 'Mongolia', currency: 'MNT', locale: 'en-MN', fiscalYearStartMonth: 1 },
  { code: 'MO', name: 'Macao', currency: 'MOP', locale: 'en-MO', fiscalYearStartMonth: 1 },
  {
    code: 'MP',
    name: 'Northern Mariana Islands',
    currency: 'USD',
    locale: 'en-MP',
    fiscalYearStartMonth: 1,
  },
  { code: 'MQ', name: 'Martinique', currency: 'EUR', locale: 'en-MQ', fiscalYearStartMonth: 1 },
  { code: 'MR', name: 'Mauritania', currency: 'MRU', locale: 'en-MR', fiscalYearStartMonth: 1 },
  { code: 'MS', name: 'Montserrat', currency: 'XCD', locale: 'en-MS', fiscalYearStartMonth: 1 },
  { code: 'MT', name: 'Malta', currency: 'EUR', locale: 'en-MT', fiscalYearStartMonth: 1 },
  { code: 'MU', name: 'Mauritius', currency: 'MUR', locale: 'en-MU', fiscalYearStartMonth: 1 },
  { code: 'MV', name: 'Maldives', currency: 'MVR', locale: 'en-MV', fiscalYearStartMonth: 1 },
  { code: 'MW', name: 'Malawi', currency: 'MWK', locale: 'en-MW', fiscalYearStartMonth: 1 },
  { code: 'MX', name: 'Mexico', currency: 'MXN', locale: 'en-MX', fiscalYearStartMonth: 1 },
  { code: 'MY', name: 'Malaysia', currency: 'MYR', locale: 'en-MY', fiscalYearStartMonth: 1 },
  { code: 'MZ', name: 'Mozambique', currency: 'MZN', locale: 'en-MZ', fiscalYearStartMonth: 1 },
  { code: 'NA', name: 'Namibia', currency: 'NAD', locale: 'en-NA', fiscalYearStartMonth: 1 },
  { code: 'NC', name: 'New Caledonia', currency: 'XPF', locale: 'en-NC', fiscalYearStartMonth: 1 },
  { code: 'NE', name: 'Niger', currency: 'XOF', locale: 'en-NE', fiscalYearStartMonth: 1 },
  { code: 'NF', name: 'Norfolk Island', currency: 'AUD', locale: 'en-NF', fiscalYearStartMonth: 1 },
  { code: 'NG', name: 'Nigeria', currency: 'NGN', locale: 'en-NG', fiscalYearStartMonth: 1 },
  { code: 'NI', name: 'Nicaragua', currency: 'NIO', locale: 'en-NI', fiscalYearStartMonth: 1 },
  { code: 'NL', name: 'Netherlands', currency: 'EUR', locale: 'en-NL', fiscalYearStartMonth: 1 },
  { code: 'NO', name: 'Norway', currency: 'NOK', locale: 'en-NO', fiscalYearStartMonth: 1 },
  { code: 'NP', name: 'Nepal', currency: 'NPR', locale: 'en-NP', fiscalYearStartMonth: 1 },
  { code: 'NR', name: 'Nauru', currency: 'AUD', locale: 'en-NR', fiscalYearStartMonth: 1 },
  { code: 'NU', name: 'Niue', currency: 'NZD', locale: 'en-NU', fiscalYearStartMonth: 1 },
  { code: 'NZ', name: 'New Zealand', currency: 'NZD', locale: 'en-NZ', fiscalYearStartMonth: 4 },
  { code: 'OM', name: 'Oman', currency: 'OMR', locale: 'en-OM', fiscalYearStartMonth: 1 },
  { code: 'PA', name: 'Panama', currency: 'PAB', locale: 'en-PA', fiscalYearStartMonth: 1 },
  { code: 'PE', name: 'Peru', currency: 'PEN', locale: 'en-PE', fiscalYearStartMonth: 1 },
  {
    code: 'PF',
    name: 'French Polynesia',
    currency: 'XPF',
    locale: 'en-PF',
    fiscalYearStartMonth: 1,
  },
  {
    code: 'PG',
    name: 'Papua New Guinea',
    currency: 'PGK',
    locale: 'en-PG',
    fiscalYearStartMonth: 1,
  },
  { code: 'PH', name: 'Philippines', currency: 'PHP', locale: 'en-PH', fiscalYearStartMonth: 1 },
  { code: 'PK', name: 'Pakistan', currency: 'PKR', locale: 'en-PK', fiscalYearStartMonth: 1 },
  { code: 'PL', name: 'Poland', currency: 'PLN', locale: 'en-PL', fiscalYearStartMonth: 1 },
  {
    code: 'PM',
    name: 'Saint Pierre and Miquelon',
    currency: 'EUR',
    locale: 'en-PM',
    fiscalYearStartMonth: 1,
  },
  { code: 'PN', name: 'Pitcairn', currency: 'NZD', locale: 'en-PN', fiscalYearStartMonth: 1 },
  { code: 'PR', name: 'Puerto Rico', currency: 'USD', locale: 'en-PR', fiscalYearStartMonth: 1 },
  {
    code: 'PS',
    name: 'Palestine, State of',
    currency: 'ILS',
    locale: 'en-PS',
    fiscalYearStartMonth: 1,
  },
  { code: 'PT', name: 'Portugal', currency: 'EUR', locale: 'en-PT', fiscalYearStartMonth: 1 },
  { code: 'PW', name: 'Palau', currency: 'USD', locale: 'en-PW', fiscalYearStartMonth: 1 },
  { code: 'PY', name: 'Paraguay', currency: 'PYG', locale: 'en-PY', fiscalYearStartMonth: 1 },
  { code: 'QA', name: 'Qatar', currency: 'QAR', locale: 'en-QA', fiscalYearStartMonth: 1 },
  { code: 'RE', name: 'Réunion', currency: 'EUR', locale: 'en-RE', fiscalYearStartMonth: 1 },
  { code: 'RO', name: 'Romania', currency: 'RON', locale: 'en-RO', fiscalYearStartMonth: 1 },
  { code: 'RS', name: 'Serbia', currency: 'RSD', locale: 'en-RS', fiscalYearStartMonth: 1 },
  {
    code: 'RU',
    name: 'Russian Federation',
    currency: 'RUB',
    locale: 'en-RU',
    fiscalYearStartMonth: 1,
  },
  { code: 'RW', name: 'Rwanda', currency: 'RWF', locale: 'en-RW', fiscalYearStartMonth: 1 },
  { code: 'SA', name: 'Saudi Arabia', currency: 'SAR', locale: 'en-SA', fiscalYearStartMonth: 1 },
  {
    code: 'SB',
    name: 'Solomon Islands',
    currency: 'SBD',
    locale: 'en-SB',
    fiscalYearStartMonth: 1,
  },
  { code: 'SC', name: 'Seychelles', currency: 'SCR', locale: 'en-SC', fiscalYearStartMonth: 1 },
  { code: 'SD', name: 'Sudan', currency: 'SDG', locale: 'en-SD', fiscalYearStartMonth: 1 },
  { code: 'SE', name: 'Sweden', currency: 'SEK', locale: 'en-SE', fiscalYearStartMonth: 1 },
  { code: 'SG', name: 'Singapore', currency: 'SGD', locale: 'en-SG', fiscalYearStartMonth: 1 },
  {
    code: 'SH',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    currency: 'SHP',
    locale: 'en-SH',
    fiscalYearStartMonth: 1,
  },
  { code: 'SI', name: 'Slovenia', currency: 'EUR', locale: 'en-SI', fiscalYearStartMonth: 1 },
  {
    code: 'SJ',
    name: 'Svalbard and Jan Mayen',
    currency: 'NOK',
    locale: 'en-SJ',
    fiscalYearStartMonth: 1,
  },
  { code: 'SK', name: 'Slovakia', currency: 'EUR', locale: 'en-SK', fiscalYearStartMonth: 1 },
  { code: 'SL', name: 'Sierra Leone', currency: 'SLE', locale: 'en-SL', fiscalYearStartMonth: 1 },
  { code: 'SM', name: 'San Marino', currency: 'EUR', locale: 'en-SM', fiscalYearStartMonth: 1 },
  { code: 'SN', name: 'Senegal', currency: 'XOF', locale: 'en-SN', fiscalYearStartMonth: 1 },
  { code: 'SO', name: 'Somalia', currency: 'SOS', locale: 'en-SO', fiscalYearStartMonth: 1 },
  { code: 'SR', name: 'Suriname', currency: 'SRD', locale: 'en-SR', fiscalYearStartMonth: 1 },
  { code: 'SS', name: 'South Sudan', currency: 'SSP', locale: 'en-SS', fiscalYearStartMonth: 1 },
  {
    code: 'ST',
    name: 'Sao Tome and Principe',
    currency: 'STN',
    locale: 'en-ST',
    fiscalYearStartMonth: 1,
  },
  { code: 'SV', name: 'El Salvador', currency: 'USD', locale: 'en-SV', fiscalYearStartMonth: 1 },
  {
    code: 'SX',
    name: 'Sint Maarten (Dutch part)',
    currency: 'ANG',
    locale: 'en-SX',
    fiscalYearStartMonth: 1,
  },
  {
    code: 'SY',
    name: 'Syrian Arab Republic',
    currency: 'SYP',
    locale: 'en-SY',
    fiscalYearStartMonth: 1,
  },
  { code: 'SZ', name: 'Eswatini', currency: 'SZL', locale: 'en-SZ', fiscalYearStartMonth: 1 },
  {
    code: 'TC',
    name: 'Turks and Caicos Islands',
    currency: 'USD',
    locale: 'en-TC',
    fiscalYearStartMonth: 1,
  },
  { code: 'TD', name: 'Chad', currency: 'XAF', locale: 'en-TD', fiscalYearStartMonth: 1 },
  {
    code: 'TF',
    name: 'French Southern Territories',
    currency: 'EUR',
    locale: 'en-TF',
    fiscalYearStartMonth: 1,
  },
  { code: 'TG', name: 'Togo', currency: 'XOF', locale: 'en-TG', fiscalYearStartMonth: 1 },
  { code: 'TH', name: 'Thailand', currency: 'THB', locale: 'en-TH', fiscalYearStartMonth: 1 },
  { code: 'TJ', name: 'Tajikistan', currency: 'TJS', locale: 'en-TJ', fiscalYearStartMonth: 1 },
  { code: 'TK', name: 'Tokelau', currency: 'NZD', locale: 'en-TK', fiscalYearStartMonth: 1 },
  { code: 'TL', name: 'Timor-Leste', currency: 'USD', locale: 'en-TL', fiscalYearStartMonth: 1 },
  { code: 'TM', name: 'Turkmenistan', currency: 'TMT', locale: 'en-TM', fiscalYearStartMonth: 1 },
  { code: 'TN', name: 'Tunisia', currency: 'TND', locale: 'en-TN', fiscalYearStartMonth: 1 },
  { code: 'TO', name: 'Tonga', currency: 'TOP', locale: 'en-TO', fiscalYearStartMonth: 1 },
  { code: 'TR', name: 'Turkey', currency: 'TRY', locale: 'en-TR', fiscalYearStartMonth: 1 },
  {
    code: 'TT',
    name: 'Trinidad and Tobago',
    currency: 'TTD',
    locale: 'en-TT',
    fiscalYearStartMonth: 1,
  },
  { code: 'TV', name: 'Tuvalu', currency: 'AUD', locale: 'en-TV', fiscalYearStartMonth: 1 },
  {
    code: 'TW',
    name: 'Taiwan, Province of China',
    currency: 'TWD',
    locale: 'en-TW',
    fiscalYearStartMonth: 1,
  },
  {
    code: 'TZ',
    name: 'Tanzania, United Republic of',
    currency: 'TZS',
    locale: 'en-TZ',
    fiscalYearStartMonth: 1,
  },
  { code: 'UA', name: 'Ukraine', currency: 'UAH', locale: 'en-UA', fiscalYearStartMonth: 1 },
  { code: 'UG', name: 'Uganda', currency: 'UGX', locale: 'en-UG', fiscalYearStartMonth: 1 },
  {
    code: 'UM',
    name: 'United States Minor Outlying Islands',
    currency: 'USD',
    locale: 'en-UM',
    fiscalYearStartMonth: 1,
  },
  { code: 'US', name: 'United States', currency: 'USD', locale: 'en-US', fiscalYearStartMonth: 1 },
  { code: 'UY', name: 'Uruguay', currency: 'UYU', locale: 'en-UY', fiscalYearStartMonth: 1 },
  { code: 'UZ', name: 'Uzbekistan', currency: 'UZS', locale: 'en-UZ', fiscalYearStartMonth: 1 },
  { code: 'VA', name: 'Holy See', currency: 'EUR', locale: 'en-VA', fiscalYearStartMonth: 1 },
  {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    currency: 'XCD',
    locale: 'en-VC',
    fiscalYearStartMonth: 1,
  },
  { code: 'VE', name: 'Venezuela', currency: 'VES', locale: 'en-VE', fiscalYearStartMonth: 1 },
  {
    code: 'VG',
    name: 'Virgin Islands, British',
    currency: 'USD',
    locale: 'en-VG',
    fiscalYearStartMonth: 1,
  },
  {
    code: 'VI',
    name: 'Virgin Islands, US',
    currency: 'USD',
    locale: 'en-VI',
    fiscalYearStartMonth: 1,
  },
  { code: 'VN', name: 'Viet Nam', currency: 'VND', locale: 'en-VN', fiscalYearStartMonth: 1 },
  { code: 'VU', name: 'Vanuatu', currency: 'VUV', locale: 'en-VU', fiscalYearStartMonth: 1 },
  {
    code: 'WF',
    name: 'Wallis and Futuna',
    currency: 'XPF',
    locale: 'en-WF',
    fiscalYearStartMonth: 1,
  },
  { code: 'WS', name: 'Samoa', currency: 'WST', locale: 'en-WS', fiscalYearStartMonth: 1 },
  { code: 'YE', name: 'Yemen', currency: 'YER', locale: 'en-YE', fiscalYearStartMonth: 1 },
  { code: 'YT', name: 'Mayotte', currency: 'EUR', locale: 'en-YT', fiscalYearStartMonth: 1 },
  { code: 'ZA', name: 'South Africa', currency: 'ZAR', locale: 'en-ZA', fiscalYearStartMonth: 3 },
  { code: 'ZM', name: 'Zambia', currency: 'ZMW', locale: 'en-ZM', fiscalYearStartMonth: 1 },
  { code: 'ZW', name: 'Zimbabwe', currency: 'ZWG', locale: 'en-ZW', fiscalYearStartMonth: 1 },
];

const BY_CODE = new Map(ISO_COUNTRIES.map((c) => [c.code, c]));

export function isoCountry(code) {
  return BY_CODE.get(code.toUpperCase());
}

export function defaultCurrencyFor(code) {
  return isoCountry(code)?.currency ?? 'USD';
}

/** SEPA / international fallback for any country without a configured schema. */
export const GENERIC_FALLBACK_FIELDS = [
  { key: 'accountName', label: 'Account holder name', type: 'text', required: true },
  {
    key: 'iban',
    label: 'IBAN',
    type: 'text',
    required: true,
    regex: '^[A-Z]{2}[0-9A-Z]{13,32}$',
    checksumType: 'IBAN',
    example: 'DE89370400440532013000',
  },
  { key: 'bic', label: 'BIC / SWIFT', type: 'text', required: false, example: 'DEUTDEFF' },
];
